import { Inter } from "next/font/google";
import StoreProvider from "./StoreProvider";
import DefaultCounter from "@/components/default-values/DefaultCounter";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <DefaultCounter />
          <main>{children}</main>
        </StoreProvider>
      </body>
    </html>
  );
}
